{
    "name": "Generando Importador de Productos",
    "summary": "Importador de Productos",
    "category": "crm",
    "images": [],
    "version": "1.0.7",
    "application": True,
    "author": "Ahorasoft",
    "support": "soporte@ahorasoft.com",
    "website": "http://www.ahorasoft.com",
    "depends": [
        "crm",
        "sale",
        'base',
        'sale_management',
        'purchase',
        'report_xlsx',
        'sale_purchase',
    ],
    'data': [
        'views/as_importar_productos.xml',
        'views/as_importar_productos_check.xml',
        
        'views/as_product_template.xml',
        'views/as_product_descontinuados.xml',
        'wizard/as_product_report.xml',
        'security/ir.model.access.csv',
        'views/as_menus.xml',
        'data/data.xml',
    ],
    "auto_install": False,
    "installable": True,
}